# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='other_ingredients',
            field=models.ManyToManyField(to='ingredients.Ingredient'),
        ),
    ]
