version: '2'
services:
  db:
    image: postgres
    ports:
      - "54325:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8005:8000"
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
